### ISSUE TITLE
Configure firewall from docker-compose.yml

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/openwrt-docker#16]
Hi @AlbrechtL ,

To setup the container I've found a trouble:
- In the initial setup, in some use cases, you need to go to the console (using the web VNC) to execute the command/s `/usr/bin/fw_wan_open_http` and/or `/usr/bin/fw_wan_open_ssh`.

However, I feel this is wasted time and unnecessary.
Why not provide an environment variable to enable/disable them?
For example:
```
    environment:
      # Enable/disable internal firewall for...
      FIREWALL_HTTP_PASS: "true" # port open, equivalent to run the script  /usr/bin/fw_wan_open_http
      FIREWALL_SSH_PASS: "true"  # port open, equivalent to run the script  /usr/bin/fw_wan_open_ssh
```

I know you might say: Well, LAN interfaces have it. But I'm running with `WAN_IF: "host"` and `LAN_IF: "none"` because running on Windows+WSL2+DockerDesktop I need to pass the LAN interface using a USB device.

What you think?
